title: Foundation Bookkeeping Blog
description: Financial insights for small businesses
theme: minima
url: "https://foundationbookkeeping.net"
baseurl: ""

markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "services.md"
    values:
      layout: "page"
# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/
include:
  - services.md
  - how-it-works.md
